deployment:
  tasks:
    - export DEPLOYPATH=/home/glowhubi/glowhub_back
    - /bin/cp -R app bootstrap config database public resources routes storage artisan composer.json composer.lock $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH/vendor
    - /bin/cp .env $DEPLOYPATH
